import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/PageComponents/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full overflow-x-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full m-0 overflow-x-hidden`}
      >
        <div className="w-full min-h-screen flex flex-col items-center">
          <main className="w-full flex-grow bg-gray-900 flex flex-col items-center justify-center">
            <Header />
            <div className="w-full flex flex-col items-center justify-center min-h-screen">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
